### ISSUE TITLE
Playlist creation returning 401 / Invalid Playlist URI.

### ISSUE THREAD

**Issue by markd2** [spotify/ios-streaming-sdk#945]
## Description

com.spotify.ios-sdk Code=401 "Invalid Playlist URI" 

`-[SPTPlaylistList createPlaylistWithName:forUser:publicFlag:accessToken:callback:]` is returning 401 errors ("Invalid Playlist URI")

### Versions

Not sure right now.  Filing because this is identical to a problem from September: (Existing iOS SDK – Playlist Access is Broken (401 error – Invalid Playlist URI))[https://github.com/spotify/ios-sdk/issues/12] and the fix was something on the Spotify server-side.

### Severity
Catastrophic

## Steps to Reproduce

Here's how I'm making a temporary playlist:

```
        let username = auth.session.canonicalUsername ?? ""
        trace("canonical username is \(username)")
        SPTPlaylistList.createPlaylist(withName: "iClassBuilder Player Playlist", 
                                       forUser: username,
                                       publicFlag: false, 
                                       accessToken: auth.session.accessToken)
        { (error, playlistSnapshot) in
            if let error = error {
                trace("error creating playbackPlaylist: \(error)") // and other error handling
            }
```

Username is `borkware` (but this is happening to all of our users.)  A fresh login and in-app auth is happening.

### Actual behaviour

The returned error is:

```
error creating playbackPlaylist: Error Domain=com.spotify.ios-sdk Code=401 "Invalid Playlist URI" UserInfo={NSLocalizedDescription=Invalid Playlist URI}
```

### Expected behaviour

Creates the playlist.

**Comment by zackfletch00** [comment]
My in-market app is also seeing this issue.  Like [spotify/ios-sdk/issues/12](https://github.com/spotify/ios-sdk/issues/12), it is also blocking all access to view and play back user playlists, in addition to blocking playlist creation.

**Comment by zackfletch00** [comment]
This is due to (perhaps overzealous) input validation code inside of SPTPlaylistSnapshot. [SPTPlaylistSnapshot createRequestForPlaylistWithURI: accessToken: market: error:] contains the following code, which aborts the playlist request due to a suspected bad URI:

```
    + (NSURLRequest *)createRequestForPlaylistWithURI:(NSURL *)uri
									  accessToken:(NSString *)accessToken
										   market:(NSString *)market
											error:(NSError **)error {
	NSArray *uriComponents = [[uri absoluteString] componentsSeparatedByString:@":"];
	
	if (uriComponents.count < 4 ||
		uriComponents.count > 5) {
		[SPTRequest setErrorCode:401 withDescription:@"Invalid Playlist URI" toError:error];
		return nil;
	}
	
	if (![[uriComponents objectAtIndex:0] isEqualToString:@"spotify"] ||
		![[uriComponents objectAtIndex:1] isEqualToString:@"user"]) {
		[SPTRequest setErrorCode:401 withDescription:@"Invalid Playlist URI" toError:error];
		return nil;
	}
        ...
    }
```
**This code is likely still included in most apps on the market using the streaming SDK**, unless the developers had been closely monitoring [the Web API news announcements](https://developer.spotify.com/community/news/2019/01/15/update-changes-to-playlist-uris/) and had a painless path to release an update to the App Store by this time.  In my case, I am still blocked by Apple from updating my application, and this issue is affecting several hundred users in production today, unless the change can be rolled back, or a hotfix can be made to return old URIs to iOS Streaming SDK users due to the broken code above.

**Comment by markd2** [comment]
@zackfletch00 great intel. Thanks!

Hacked my local version of the metadata framework, and it's successfully creating an empty playlist (can see it in the Spotify desktop app). When I try to `replaceTracksInPlaylist:withAccessToken:callback:" it doesn't result in any error, but nothing is added to the playlist. :-(

**Comment by Anders27** [comment]
Why not download and use Spotify iOS Streaming SDK Beta 27?

from the "CHANGELOG.md" file:
Updates to SPTPlaylistSnapshot to support V2 playlist URI's. For for information see https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

It fixes this problem.

But sooner or later this SDK will break if Spotify decides to change something else in their infrastructure. So please, tell us that you will continue to maintain this SDK. The newer SDK is NOT a good replacement since it's not possible to access the raw audio samples. This "ios-streaming-sdk" is something no other music streaming company offers. I'm quite sure our apps that uses this SDK generates many new paying Spotify subscribers, so maintaining this SDK will pay off in the long run.
It's already a very mature and stable SDK and the very few bugs it contains should be easy to fix.

**Comment by markd2** [comment]
@Anders27 Brilliant! I don't know how I missed that.  It covers my needs for now and gets my users back up and running.

And agreed the new SDK is incomplete.  I just want to take a list of `spotify:track:....` URIs and play them sequentially.  That's surprisingly hard with the new SDK.
